### ISSUE TITLE
JS breaks when adding feature box to post

### ISSUE THREAD

**Issue by acorbi** [oeco/wp-feature-box#4]
Testing on WP MU 4.1
Firefox 35.0.
Chrome

After installing and activating the plugin and following the instructions i go to **Add new post** and click the ** add feature box** button.
![feature-image](https://cloud.githubusercontent.com/assets/384894/6060287/ab03e466-ad3b-11e4-8528-480ba202d0ea.jpg)
Following error is thrown on the javascript console.
![feature-image1](https://cloud.githubusercontent.com/assets/384894/6060286/ab036b1c-ad3b-11e4-85a4-37e08a50ea10.jpg)
Also tried adding the feature box from the sidebar menu in the WP admin area.

**Comment by messi655** [comment]
Hi Alex, what's the plugin you has installed?

**Comment by acorbi** [comment]
@messi655 wp-feature-box (https://github.com/oeco/wp-feature-box). The wordpress plugin you are commenting about right now..

**Comment by acorbi** [comment]
@miguelpeixe I analize the issue and it is definitelly a compatibility Issue with WP > 3.9 that introduced tinymce version 4.0
Please read:
https://make.wordpress.org/core/2014/01/18/tinymce-4-0-is-in-core/
http://www.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x
http://www.tinymce.com/wiki.php/Plugin:compat3x

**Comment by miguelpeixe** [comment]
fixed d201c52c81a8527123553fd7e186522b47b52238

**Comment by miguelpeixe** [comment]
fixed on version 0.1.3

**Comment by acorbi** [comment]
@miguelpeixe I installed the latest code on master. Still having a javascript issue when loading the "Add new post" screen.
![bildschirmfoto 2015-02-06 um 17 27 42](https://cloud.githubusercontent.com/assets/384894/6082997/d48f2e68-ae25-11e4-92b7-5f161162ec08.png)

**Comment by miguelpeixe** [comment]
Did you get the 0.1.3 or the 0.1.2?
The 0.1.3 everything is fixed

**Comment by acorbi** [comment]
Ok, now its working. Probably my mistake, Thanks for the quick reaction!
